dist: jammy

language: php

php:
- 8.1

notifications:
  email:
  - team@appwrite.io

services:
- docker

before_install:
- docker-compose up -d
- sleep 60

before_script: composer install

script:
- vendor/bin/phpunit
